### PR TITLE
Try to use reusable build

### PR DESCRIPTION
**Pull request by Ughuuu**

### CODE REVIEW

**Comment by Ughuuu** [comment]
@aiaimimi0920 I tried splitting in this PR the functions so the API is clearer and it can be debugged easier.
Right now the API only has:
- `transcribe`
- `resample`
- `voice_activity_detection`

I checked and the resample was actually a botleneck all this time for performance, there is a parameter to the resample(in godot voice is sampled at a higher rate, so it needs to be downsampled). We were using until now:
- `SRC_SINC_BEST_QUALITY` - on longer audio this takes a long time, maybe 1s even.
- `SRC_SINC_FASTEST` - this is really fast, even on longer audio, maybe 0.02s.

I think threading should be done in gdscript, also the post processing. As for vad, I think we could make the function return more than a boolean, maybe even time when it occurs.

Also in this PR I am adding the building system to be reusable.

**Comment by fire** [comment]
If it's possible can you separate the api changes from "use reusable build".

**Comment by Ughuuu** [comment]
Uh, I'll see. Still working on this pr.

**Comment by aiaimimi0920** [comment]
Yes, thank you in advance for your modifications

**Comment by fire** [comment]
Hiya, I recommend merging the builds that work and then individually fix the remaining ones.

**Comment by Ughuuu** [comment]
Sorry, you get a lot of notifications from this, dont you?

**Comment by Ughuuu** [comment]
@aiaimimi0920 
Also added to readme:


## Initial Prompt

For Chinese, if you want to select between Traditional and Simplified, you need to provide an initial prompt with the one you want, and then the model should keep that same one going. See [Whisper Discussion #277](https://github.com/openai/whisper/discussions/277).

Also, if you have problems with punctuation, you can give it an initial prompt with punctuation. See [Whisper Discussion #194](https://github.com/openai/whisper/discussions/194).

**Pull request merged**
