### PR TITLE
Use godot `thread`

### PR DESCRIPTION
**Pull request by aiaimimi0920**
After debugging, I found that it was because of using `MutexLock lock(s_mutex)`; is not unlocked correctly, causing the final thread to freeze.

If you use `s_mutex.lock()` and `s_mutex.unlock()` there will be no problem

### CODE REVIEW

**Review by fire — APPROVED** [review]
Paper review looks ok, but the proof is when we run the demo for like 20 minutes with no crashing. I'm not able to spend much time on this today.

**Comment by fire** [comment]
Did something break on the cicd?

**Comment by fire** [comment]
I'll merge it once it passes on your cicd. 
image

**Comment by aiaimimi0920** [comment]
@fire 
It has been compiled and passed. This is a local windows test.

https://github.com/V-Sekai/godot-whisper/assets/153103332/865f9eaa-4952-4925-a2d4-f8dad6260bdb

**Comment by fire** [comment]
Thanks

**Comment by Ughuuu** [comment]
It's strange that the cicd doesn't start for his builds. Maybe we need to set up some option. I'll check

**Pull request merged**
